export const MUSCLE_GROUPS = [
  'Chest',
  'Upper Chest',
  'Mid Chest',
  'Lower Chest',
  'Back',
  'Upper Back',
  'Mid Back',
  'Lower Back',
  'Shoulders',
  'Front Shoulders',
  'Side Shoulders',
  'Rear Shoulders',
  'Arms',
  'Biceps',
  'Triceps',
  'Forearms',
  'Legs',
  'Quads',
  'Hamstrings',
  'Calves',
  'Glutes',
  'Upper Glutes',
  'Lower Glutes',
  'Core',
  'Upper Abs',
  'Lower Abs',
  'Obliques',
  'Full Body',
];
